spring:
   config:
      import: optional:file:.env[.properties]
   main:
      web-application-type: servlet
   data:
     mongodb:
         uri: ${PASSWD}
         database: DB
   web:
      resources:
           add-mappings: false
   mvc:
      throw-exception-if-no-handler-found: true
   
server: 
   port: 8000
  

